# Generated by Django 5.2.1 on 2025-05-29 19:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicePackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('items', models.TextField(help_text='Enter a comma-separated list of items or features')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('sample_image', models.ImageField(blank=True, null=True, upload_to='packages/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='packages', to='core.service')),
            ],
        ),
    ]
