# Generated by Django 5.2.1 on 2025-05-30 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='selected_packages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='event',
            name='used_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
