# Generated by Django 5.2.1 on 2025-05-30 16:15

import core.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_event_selected_packages_event_used_budget'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='selected_packages',
        ),
        migrations.RemoveField(
            model_name='event',
            name='used_budget',
        ),
        migrations.AddField(
            model_name='event',
            name='status',
            field=models.CharField(default='confirmed', max_length=20),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=core.models.generate_uuid, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='PackageBooking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='core.event')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicepackage')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service')),
            ],
        ),
    ]
